// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webApiKey'].toString(),
    appId: '1:660560608016:web:5bf0dd0e3eda13cc234395',
    messagingSenderId: '660560608016',
    projectId: 'venture-guide',
    authDomain: 'venture-guide.firebaseapp.com',
    storageBucket: 'venture-guide.appspot.com',
    measurementId: 'G-NFSV376SW5',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidApiKey'].toString(),
    appId: '1:660560608016:android:16916a0c51888b8d234395',
    messagingSenderId: '660560608016',
    projectId: 'venture-guide',
    storageBucket: 'venture-guide.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['iosApiKey'].toString(),
    appId: '1:660560608016:ios:7c539d791d4d36ce234395',
    messagingSenderId: '660560608016',
    projectId: 'venture-guide',
    storageBucket: 'venture-guide.appspot.com',
    iosBundleId: 'br.com.schuster.everton.ventureGuide',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['iosApiKey'].toString(),
    appId: '1:660560608016:ios:87cfb321939caffe234395',
    messagingSenderId: '660560608016',
    projectId: 'venture-guide',
    storageBucket: 'venture-guide.appspot.com',
    iosBundleId: 'br.com.schuster.everton.ventureGuide.RunnerTests',
  );
}
