// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:venture_guide/app/map/domain/models/system_settings/system_markers_init.dart'
    as prefix1;
import 'package:venture_guide/app/reflector.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'SystemMarkersInit',
            r'.SystemMarkersInit',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 4],
            const <int>[5, 6, 7, 8, 9, 1, 2, 3],
            const <int>[],
            -1,
            {},
            {},
            {
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.SystemMarkersInit.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'isMarkerLoad', 67239941, 0,
            const prefix0.Reflector(), -1, 1, 1, const <int>[], const []),
        r.MethodMirrorImpl(r'toJson', 35651586, 0, -1, 2, 3, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 2),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 3),
        r.MethodMirrorImpl(r'fromJson', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 4, 4, const <int>[],
            const <int>[2], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1,
            const <int>[], const <int>[3], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'json', 84017158, 4, const prefix0.Reflector(),
            -1, 8, 9, null, const [], null, null),
        r.ParameterMirrorImpl(
            r'_isMarkerLoad',
            67240038,
            3,
            const prefix0.Reflector(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'other', 134348806, 5, const prefix0.Reflector(),
            -1, 10, 10, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            7,
            const prefix0.Reflector(),
            -1,
            11,
            11,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.SystemMarkersInit,
        bool,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        bool,
        String,
        int,
        Type,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'isMarkerLoad': (dynamic instance) => instance.isMarkerLoad
      },
      {
        r'isMarkerLoad=': (dynamic instance, value) =>
            instance.isMarkerLoad = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(
                'package:venture_guide/app/map/domain/models/system_settings/system_markers_init.dart'),
            const prefix0.Reflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
